In [ ]:
#Import Libraries
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [ ]:
#Load the Dataset
df=pd.read_csv("/content/bank.csv", delimiter=';')
print("Dataset Loaded")

Dataset Loaded

In [ ]:
df.shape

(4521, 17)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        4521 non-null   int64
 1   job        4521 non-null   object
 2   marital    4521 non-null   object
 3   education  4521 non-null   object
 4   default    4521 non-null   object
 5   balance    4521 non-null   int64
 6   housing    4521 non-null   object
 7   loan       4521 non-null   object
 8   contact    4521 non-null   object
 9   day        4521 non-null   int64
 10  month      4521 non-null   object
 11  duration   4521 non-null   int64
 12  campaign   4521 non-null   int64
 13  pdays      4521 non-null   int64
 14  previous   4521 non-null   int64
 15  poutcome   4521 non-null   object
 16  y          4521 non-null   object
dtypes: int64(7), object(10)
memory usage: 600.6+ KB

In [ ]:
df.describe()

               age       balance  ...        pdays     previous
count  4521.000000   4521.000000  ...  4521.000000  4521.000000
mean     41.170095   1422.657819  ...    39.766645     0.542579
std      10.576211   3009.638142  ...   100.121124     1.693562
min      19.000000  -3313.000000  ...    -1.000000     0.000000
25%      33.000000     69.000000  ...    -1.000000     0.000000
50%      39.000000    444.000000  ...    -1.000000     0.000000
75%      49.000000   1480.000000  ...    -1.000000     0.000000
max      87.000000  71188.000000  ...   871.000000    25.000000

[8 rows x 7 columns]

In [ ]:
df.head()

   age          job  marital  education  ... pdays  previous poutcome   y
0   30   unemployed  married    primary  ...    -1         0  unknown  no
1   33     services  married  secondary  ...   339         4  failure  no
2   35   management   single   tertiary  ...   330         1  failure  no
3   30   management  married   tertiary  ...    -1         0  unknown  no
4   59  blue-collar  married  secondary  ...    -1         0  unknown  no

[5 rows x 17 columns]

In [ ]:
duplicate=df.duplicated().sum()
print("No.of Duplicate Rows: ",duplicate)

No.of Duplicate Rows:  0

In [ ]:
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [ ]:
#Find Categorical and Numerical columns
numerical_cols=df.select_dtypes(include=['int64']).columns
categorical_cols=df.select_dtypes(include=['object']).columns
print("Numerical Columns: ",numerical_cols)
print("Categorical Columns: ",categorical_cols)

Numerical Columns:  Index(['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous'], dtype='object')
Categorical Columns:  Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'poutcome', 'y'],
      dtype='object')

In [ ]:
#Separete Features and target values
x=df.iloc[:,:-1]
y=df.iloc[:,-1]
y = y.map({'no': 0, 'yes': 1})

In [ ]:
#split the data into train and test
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
#Identify categorical data of x
categorical_x=x.select_dtypes(include=['object','category']).columns
print(categorical_x)

Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'month', 'poutcome'],
      dtype='object')

In [ ]:
#Apply one-hot encoding
x_test=pd.get_dummies(x_test, columns=categorical_x, drop_first=True)
x_train=pd.get_dummies(x_train, columns=categorical_x, drop_first=True)

x_train,x_test=x_train.align(x_test,join='outer',axis=1, fill_value=0)

In [ ]:
#standardization
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [ ]:
#Model Building
from sklearn.svm import LinearSVC
model=LinearSVC(random_state=42)
model.fit(x_train,y_train)

LinearSVC(random_state=42)

In [ ]:
#Predictions
y_pred=model.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy: ",accuracy)

Accuracy:  0.9060773480662984

In [ ]:
#Evalution Metrices
confusion_mat=confusion_matrix(y_test,y_pred)
print("Confusion Matrix : ",confusion_mat)

Confusion Matrix :  [[791  16]
 [ 69  29]]

In [ ]:
#classification report
classification_rep=classification_report(y_test,y_pred)
print("Classification Report:")
print(classification_rep)

Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.98      0.95       807
           1       0.64      0.30      0.41        98

    accuracy                           0.91       905
   macro avg       0.78      0.64      0.68       905
weighted avg       0.89      0.91      0.89       905